name: Playwright Tests
on:
  workflow_dispatch:
jobs:
  test:
    name: Run Playwright tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.40.0-jammy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: package-lock.json
      - name: Install NPM dependencies
        run: npm ci
      - name: Run Playwright tests
        run: npm run test
        env:
          HOME: /root
      - name: Upload report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 1
  publish:
    if: always()
    name: Push report to GH Pages
    needs: [ test ] # publish runs after tests are done
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        id: download
      - name: Publish to GH Pages
        uses: peaceiris/actions-gh-pages@v3.7.3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{steps.download.outputs.download-path}}

