name: UI Tests split by project
on:
  workflow_dispatch:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        project: [chromium, firefox, webkit]
    name: Run UI tests
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.45.1-jammy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json
      - name: Install NPM dependencies
        run: npm ci
      - name: Run UI tests for ${{matrix.project}}
        run: npx playwright test --project=${{matrix.project}}
        env:
          HOME: /root # Needed to run firefox tests
      - name: Upload blob report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: report-${{matrix.project}}
          path: blob-report
          retention-days: 1
  merge:
    if: always()
    needs: [test]
    name: Merge and publish reports
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Download blobs
        uses: actions/download-artifact@v4
        id: download
        with:
          pattern: report-*
          merge-multiple: true
          path: all-blob-reports
      - name: Merge into HTML Report
        run: npx playwright merge-reports --reporter html ./all-blob-reports
      - name: Upload Playwright HTML report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 1
  publish:
    if: always()
    name: Push report to GH Pages
    needs: [merge] # publish results after tests are done
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Publish to GH Pages
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: playwright-report/
          publish_branch: gh-pages
