name: UI Tests split by sharding
on:
  workflow_dispatch:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4]
        shardTotal: [4]
    name: Run Playwright tests
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.45.1-jammy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json
      - name: Install NPM dependencies
        run: npm ci
      - name: Run Playwright tests
        run: npx playwright test --shard=${{matrix.shardIndex}}/${{matrix.shardTotal}}
        env:
          HOME: /root # Needed to run firefox tests
      - name: Upload blob report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: report-${{matrix.shardIndex}}
          path: blob-report
          retention-days: 1
  merge:
    if: always()
    needs: test
    uses: ./.github/workflows/merge-reports.yml
    with:
      artifact-pattern: report-*
      merged-report-name: playwright-report
  publish:
    if: always()
    needs: merge
    uses: ./.github/workflows/publish.yml
    with:
      report-name: playwright-report
      branch: gh-pages
