name: UI Tests split by sharding
on:
  workflow_dispatch:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4]
        shardTotal: [4]
    name: Run Playwright tests
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.45.1-jammy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json
      - name: Install NPM dependencies
        run: npm ci
      - name: Run Playwright tests
        run: npx playwright test --shard=${{matrix.shardIndex}}/${{matrix.shardTotal}}
        env:
          HOME: /root # Needed to run firefox tests
      - name: Upload blob report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: report-${{matrix.shardIndex}}
          path: blob-report
          retention-days: 1
  merge:
    if: always()
    needs: [test]
    name: Merge and publish reports
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Download blobs
        uses: actions/download-artifact@v4
        id: download
        with:
          pattern: report-*
          merge-multiple: true
          path: all-blob-reports
      - name: Merge into HTML Report
        run: npx playwright merge-reports --reporter html ./all-blob-reports
      - name: Upload Playwright HTML report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 1
  publish:
    if: always()
    name: Push report to GH Pages
    needs: [merge]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1 # Ensures a clean repo without previous builds

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Push report to gh-pages
        run: |
          # Switch to a new 'gh-pages' branch
          git checkout --orphan gh-pages
          # Remove all files from the old working tree
          git rm -rf .
          # Move the Playwright report files to the root of the repo
          mv playwright-report/* ./
          # Add all files for the commit
          git add .
          # Commit the changes
          git commit -m "Publishing Playwright report to GitHub Pages"
          # Force push to the 'gh-pages' branch
          git push --force origin gh-pages
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Publish to GH Pages
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: playwright-report/
          publish_branch: gh-pages
